config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "about" => "homes#about" , as: "about"
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    books_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  
  def index
    @books = Book.all
    @new_book = Book.new
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def create
  end
  
  def edit
  end
  
  def update
  end
  
  def destory
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<h1>indexページ</h1>

app/views/homes/top.html.erb
<div class="container">
  <%= render 'layouts/header' %>
  <div class="row">
    <div class="col">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p class="top-text">
        In <i class="fas fa-book"></i>Bookers,<br>
        you can share and exchange your opinions , inpressions , and emotions<br>
        about various books!
      </p>
      <div class="log-in">
        <%= link_to "Log in", new_user_registration_path %>
      </div>
      <div class="sign-up">
        <%= link_to "Sign Up", new_user_session_path %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'layouts/footer' %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<p>CopyRight Infratop.inc</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Bookers</a>
    <% if 
    <ul class="list-group list-group-horizontal">
      <li class="list-unstyled"><i class="fas fa-home"></i><%= link_to "Home", root_path %></li>
      <li class="list-unstyled"><i class="fas fa-link"></i><%= link_to "About", about_path %></li>
      <li class="list-unstyled"><i class="fas fa-user-plus"></i><%= link_to "sign up", new_user_registration_path %></li>
      <li class="list-unstyled"><i class="fas fa-sign-in-alt"></i><%= link_to "login", new_user_session_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>